name: Terraform Init and Apply
on:
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions
jobs:
  terraform-init:
    name: Terraform Init on AWS
    runs-on: ubuntu-latest
    env:
      TF_VAR_bucket_name: ${{ secrets.TF_BUCKET_NAME }}
      TF_VAR_region: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=${{ secrets.TF_BUCKET_NAME }}" \
                            -backend-config="key=terraform.tfstate" \
                            -backend-config="region=us-east-1" \
                            -backend-config="encrypt=true"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve